### ISSUE TITLE
CSV Import

### ISSUE THREAD

**Issue by FireByTrial** [TDXDigital/TPS#105]
Hey James,

I had an idea the other day while creating a pre-recorded program for my radio show. The audio software I use, and many use at the station, Reaper, has the capability of producing a .csv (comma separated value) file of all the audio/media items in a recording. Essentially it creates a spreadsheet, you can literally open it with excel, of song titles, artists, ads and spoken word segments in chronological order with time and duration information, practically a program log in itself.

Would it be possible to implement some sort of import function for .csv files into the program logging system for people who make a lot of pre-records? Certainly the formatting would have to adhere to the logging system and I've taken it upon myself to create a script for Reaper to accomplish this goal.

More often than not when I create a pre-record I am out of town and unable to complete a program log at all and they go completely forgotten and un-logged. The process of logging a show after the pre-record has aired is a tedious practice involving scrubbing through the recording all over again and logging the show as if it was happening live. The time commitment to make the pre-record itself is often much more than a live broadcast and including the extra time involved to log the show, sometimes weeks after, creates quite an inconvenience.

Let me know what you think. I believe the station could definitely benefit from more accurate and more frequent program logging and DJs would definitely benefit from a simplified and swifter method of logging pre-records when circumstances don't allow them to be at the station every week.

Cheers,

Ethan

**Comment by ckxu** [comment]
Just FYI, here's the address to do logging remotely (same username and password as for the booth computers):

https://ckxu.uleth.ca


Sean Warkentine,
Music Director at CKXU 88.3 FM
SU-162 4401 University Drive W
Lethbridge, AB, Canada
T1K 3M4

twitter.com/CKXUmusic<http://twitter.com/CKXUmusic>
facebook.com/CKXUmusic<http://facebook.com/CKXUmusic>
instagram.com/CKXUmusic<http://instagram.com/CKXUmusic>
Listen at 88.3 FM or online at www.ckxu.com

________________________________
