### ISSUE TITLE
library management playlist button

### ISSUE THREAD

**Issue by ckxu** [TDXDigital/TPS#41]
Can the playlist boolean set to on when the library management page loads?

**Comment by ckxu** [comment]
Shall I add additional needs here? or create a new one each time?

**Comment by FireByTrial** [comment]
new one please unless it is related to this issue

**Comment by FireByTrial** [comment]
functionality needs added to playlist.induct.php
```
23: $note = filter_input(INPUT_POST, "notes")?:NULL;
00:    *** ADD HERE ***
24: if($locale=="International"){
```
