### ISSUE TITLE
Legacy interface not loading

### ISSUE THREAD

**Issue by ckxu** [TDXDigital/TPS#85]
The Legacy Interface, as of this morning, loads a blank page:
https://ckxu.uleth.ca/legacy_controller.php
![screen shot 2015-09-08 at 9 22 14 am](https://cloud.githubusercontent.com/assets/12229121/9738967/2399961e-560b-11e5-97f8-42843b40fb13.png)

**Comment by FireByTrial** [comment]
should be resolved now.
